// <auto-generated />
using CityInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.API.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    partial class CityInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The one with the big apple",
                            Name = "New York city"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The one with the cathedral that was never really finished",
                            Name = "Antwerp"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The one with that bid tower.",
                            Name = "Paris"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("MyProperty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("cityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("cityId");

                    b.ToTable("PointOfInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The most visited urban park in the United States",
                            MyProperty = 1,
                            Name = "Cental park",
                            cityId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "A 102-story skyscraper located in Midtown Manhattan ",
                            MyProperty = 1,
                            Name = "Empire State Building",
                            cityId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "A gathic style cathedral, conceived by architect Jan",
                            MyProperty = 2,
                            Name = "Cathedral",
                            cityId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "The finest example of railway architecture in Belgium",
                            MyProperty = 2,
                            Name = "Antwerp Central Station",
                            cityId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "A wrought iron lattice tower on the Champs de Mars , named Tour Eiffel",
                            MyProperty = 3,
                            Name = "Eiffel Tower",
                            cityId = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "The world largest museum.",
                            MyProperty = 3,
                            Name = "The Louvre",
                            cityId = 3
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.HasOne("CityInfo.API.Entities.City", "city")
                        .WithMany("pointOfInterest")
                        .HasForeignKey("cityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");
                });

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Navigation("pointOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
